import type { HelpTutorial } from "./tutorials";

export const workflowTutorials: HelpTutorial[] = [
  {
    id: "calendar-people",
    title: "Kalender und Kolleginnen einblenden",
    description: "Eigene Termine, einzelne Personen und den Teammonat anzeigen.",
    guideId: "calendar",
    platform: "all",
    durationSeconds: 29,
    bytes: 334054,
    video: "/tutorials/v4/calendar-people.mp4",
    poster: "/tutorials/v4/calendar-people.webp",
    captions: "/tutorials/v4/calendar-people.vtt",
    steps: [
      "Zu Beginn siehst du deinen Kalender in der aktuellen Spielzeit.",
      "Tippe einen Tag an. Die Tagesliste zeigt Namen und Zeiten vollständig.",
      "Öffne die Kalenderauswahl und blende eine Kollegin ein.",
      "Wechsle zwischen Monat, Woche, Tag und Agenda.",
      "Team zeigt alle. Teammonat gibt dir den Überblick über den ganzen Monat.",
      "Zurück zu Monat und Nur ich zeigt wieder nur deine eigenen Termine.",
    ],
    schematic: false,
  },
  {
    id: "casting-photos",
    title: "Besetzung anlegen und Fotos ergänzen",
    description: "Figur und Schauspielperson verbinden und Bilder zur Besetzung hinzufügen.",
    guideId: "casting",
    platform: "all",
    durationSeconds: 18,
    bytes: 212073,
    video: "/tutorials/v4/casting-photos.mp4",
    poster: "/tutorials/v4/casting-photos.webp",
    captions: "/tutorials/v4/casting-photos.vtt",
    steps: [
      "Öffne die Produktion und wähle Besetzung.",
      "Wähle vorhandene Einträge. Neue Namen kannst du direkt anlegen oder frei eintragen.",
      "Speichere die Besetzung. Die Details mit der Bildergalerie öffnen sich direkt.",
      "Tippe auf Bilder hinzufügen und wähle ein Foto. Mehrere Bilder sind möglich.",
      "Die Bilder gehören zu dieser Besetzung. Schauspieler und Figur bleiben verknüpft.",
    ],
    schematic: false,
  },
  {
    id: "production-tasks",
    title: "Aufgaben im Stück verteilen",
    description: "Aufgabe, Verantwortliche und Checkliste anlegen und den Status ändern.",
    guideId: "tasks",
    platform: "all",
    durationSeconds: 17,
    bytes: 252625,
    video: "/tutorials/v4/production-tasks.mp4",
    poster: "/tutorials/v4/production-tasks.webp",
    captions: "/tutorials/v4/production-tasks.vtt",
    steps: [
      "Aufgaben & Sprints enthält das eigene Board dieser Produktion.",
      "Gib der Aufgabe einen klaren Titel und wähle bei Bedarf einen Sprint.",
      "Teile die Aufgabe einer oder mehreren Kolleginnen zu.",
      "Lege jeden Arbeitsschritt als eigenen Eintrag an.",
      "Ändere die Spalte auf In Arbeit. Am Handy geht das über die Auswahl auf der Karte.",
    ],
    schematic: false,
  },
  {
    id: "mask-plan-blocks",
    title: "Zeitblock im Maskenplan anlegen",
    description: "Schauspielperson, Vorlauf und Dauer festlegen und den Plan speichern.",
    guideId: "mask-plans",
    platform: "all",
    durationSeconds: 25,
    bytes: 278995,
    video: "/tutorials/v5/mask-plan-blocks.mp4",
    poster: "/tutorials/v5/mask-plan-blocks.webp",
    captions: "/tutorials/v5/mask-plan-blocks.vtt",
    steps: [
      "Hier ist eine Personalspalte vorbereitet. −30 heißt: 30 Minuten vor Beginn.",
      "Trage 30 Minuten vor Beginn und 20 Minuten Dauer ein.",
      "Wähle Alex aus der Besetzung. Der Block gehört zur gewählten Personalspalte.",
      "Mit Beginn 19:30 wird aus −30 die Uhrzeit 19:00.",
      "Übernehmen ändert zuerst den Entwurf. Plan speichern übernimmt den ganzen Ablauf.",
      "Nach dem Speichern wird die Tabelle kleiner. Plan bearbeiten öffnet sie wieder größer.",
    ],
    schematic: false,
  },
  {
    id: "look-sections",
    title: "Aufschrieb mit mehreren Textfeldern",
    description: "Aufschrieb zur Besetzung erstellen und Makeup-Schritte getrennt festhalten.",
    guideId: "looks",
    platform: "all",
    durationSeconds: 17,
    bytes: 220242,
    video: "/tutorials/v4/look-sections.mp4",
    poster: "/tutorials/v4/look-sections.webp",
    captions: "/tutorials/v4/look-sections.vtt",
    steps: [
      "Öffne Aufschriebe in der Produktion und lege einen neuen Eintrag an.",
      "Der Schauspielername wird zum Titel. Die Zuordnung zum Stück ist schon gesetzt.",
      "Wähle unter Makeup Textfeld anlegen und schreibe die erste Anweisung.",
      "Mit Textfeld hinzufügen legst du einen weiteren Schritt in derselben Kategorie an.",
      "Der gespeicherte Aufschrieb steht im Stück und in der allgemeinen Aufschrieb-Sammlung.",
    ],
    schematic: false,
  },
  {
    id: "production-time",
    title: "Zeit auf eine Produktion buchen",
    description: "Tätigkeit und Dauer einem Stück zuordnen, getrennt von deiner Anwesenheit.",
    guideId: "time",
    platform: "all",
    durationSeconds: 19,
    bytes: 270729,
    video: "/tutorials/v4/production-time.mp4",
    poster: "/tutorials/v4/production-time.webp",
    captions: "/tutorials/v4/production-time.vtt",
    steps: [
      "Öffne Produktionsstunden im Stück. Hier buchst du deine Tätigkeit. Deine gesamte Anwesenheit trägst du separat ein.",
      "Trage ein, was du gemacht hast. Die Produktion ist bereits zugeordnet.",
      "Wähle Dauer für eine Minutenbuchung. Beginn & Ende geht ebenfalls.",
      "90 Minuten sind 1,5 Stunden Produktionsarbeit. Prüfe die Angaben und speichere.",
      "Über Bearbeiten kannst du Fehler ändern. Anwesenheit erfasst du separat unter Zeit.",
    ],
    schematic: false,
  },
  {
    id: "time-history",
    title: "Frühere Wochen und Kalenderzeiten prüfen",
    description: "Alte Stunden korrigieren, freie Tage sehen und geplante Zeiten bewusst buchen.",
    guideId: "time",
    platform: "all",
    durationSeconds: 24,
    bytes: 341370,
    video: "/tutorials/v4/time-history.mp4",
    poster: "/tutorials/v4/time-history.webp",
    captions: "/tutorials/v4/time-history.vtt",
    steps: [
      "Öffne Zeit. Im Wochenverlauf siehst du frühere Wochen mit ihren Summen.",
      "ABF und Ruhetag sind Tageskennzeichnungen. Sie erzeugen keine Arbeitsstunden.",
      "Korrigiere Beginn, Ende oder Pause. Im Beispiel ergänzen wir 30 Minuten Pause.",
      "Die Summe ist aktualisiert. Wähle diese Woche, um ihre Kalenderzeiten zu prüfen.",
      "Ein Kalendertermin ist noch keine Buchung. Öffne den Vorschlag und prüfe die Zeiten.",
      "Ergänze deine echte Pause. Erst Geprüfte Zeit buchen speichert die Buchung.",
      "Anwesenheit und Produktionsarbeit haben eigene Verläufe und werden getrennt gebucht.",
    ],
    schematic: false,
  },
  {
    id: "private-chat",
    title: "Privaten Chat starten",
    description: "Eine Kollegin auswählen und eine Nachricht direkt an sie senden.",
    guideId: "chat",
    platform: "all",
    durationSeconds: 17,
    bytes: 135083,
    video: "/tutorials/v3/private-chat.mp4",
    poster: "/tutorials/v3/private-chat.webp",
    captions: "/tutorials/v3/private-chat.vtt",
    steps: [
      "Öffne Kommunikation und Chataktionen. Wähle dann Privater Chat.",
      "Direktchat verbindet zwei Personen. Für mehrere wählst du Gruppe.",
      "Prüfe den Chatnamen und schreibe deine Nachricht.",
      "Tippe auf Senden. Die Nachricht erscheint im gemeinsamen Verlauf.",
    ],
    schematic: false,
  },
];
